name: Lint against Ruff
permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write
  statuses: write
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-with-pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          python -m pip install ruff

      - name: run ruff
        run: |
          python -m ruff check ./ --fix
          python -m ruff format ./

      - name: update
        run: |
          if [ -n "$(git status --porcelain)" ]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update by ruff"
          git push
          fi

    