name: PyTest
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-with-pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          python -m pip install -e ".[dev]"

      - name: Run tests
        run: python -m pytest
